import mongoose from "mongoose";

const StaffSchema = new mongoose.Schema({
  img: String,
  staffCode:Number,
  firstName: String,
  lastName: String,
  email: String,
  phone: String,
  birthday: Date,
  gender: String,
  workplace: String,
  status: String,
  jobPosition: String,
  directManager: String,
  role: String,
  academicLevel: String,
  hourlyRate: Number,
  defaultLanguage: String,
  direction: String,
  emailSignature: String,
  otherInfo: String,
  twilioPhone: String,
  twilioWhatsappEnabled: String,
  password: String,

  // Related Info
  domicile: String,
  maritalStatus: String,
  currentAddress: String,
  nation: String,
  placeOfBirth: String,
  religion: String,
  citizenId: String,
  dateOfIssue: Date,
  placeOfIssue: String,
  resident: String,
  bankAccountNumber: String,
  bankAccountName: String,
  bankName: String,
  taxCode: String,
  epfNo: String,
  socialSecurityNo: String,
  facebook: String,
  linkedin: String,
  skype: String,
});

export default mongoose.model("StaffProfile", StaffSchema);
